import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      // Without this, a bare `border`/`border-b` utility falls back to
      // Tailwind's hardcoded gray-200 instead of the theme's dark-aware
      // --color-border — invisible/wrong-colored hairlines in dark mode.
      borderColor: {
        DEFAULT: 'var(--color-border, #e2e8f0)',
      },
      colors: {
        'background-alt': 'var(--color-background-alt, #F8F9FA)',
        'tertiary-container': 'var(--color-tertiary-container, #983c00)',
        'surface-tint': 'var(--color-surface-tint, #115cb9)',
        'surface-bright': 'var(--color-surface-bright, #f9f9ff)',
        // `primary` was a single flat colour, so every `primary-600`/`primary-400`
        // utility compiled to nothing — 271 of them across 25 files, silently, since
        // Tailwind just drops unknown classes. Components pair the themes by hand
        // (`text-primary-600 dark:text-primary-400`), so this ramp is fixed rather than
        // theme-switching, and stays in hex so the opacity modifiers already in use
        // (`dark:bg-primary-900/30`) keep working — a bare var() would break them.
        // DEFAULT keeps the original variable, so existing `bg-primary` is untouched.
        primary: {
          DEFAULT: 'var(--color-primary, #003f87)',
          50: '#eff5fd',
          100: '#dbe8fa',
          200: '#bcd5f5',
          300: '#8dbaee',
          400: '#5b9bea',
          500: '#2f79db',
          600: '#0d55b3',
          700: '#0a4795',
          800: '#003f87',
          900: '#002f66',
        },
        'error-container': 'var(--color-error-container, #ffdad6)',
        'surface-container-lowest': 'var(--color-surface-container-lowest, #ffffff)',
        'inverse-on-surface': 'var(--color-inverse-on-surface, #f0f0f9)',
        'surface-dim': 'var(--color-surface-dim, #d9d9e2)',
        'secondary-fixed': 'var(--color-secondary-fixed, #83fc8e)',
        'tertiary-fixed': 'var(--color-tertiary-fixed, #ffdbcc)',
        outline: 'var(--color-outline, #727784)',
        'on-primary': 'var(--color-on-primary, #ffffff)',
        'on-background': 'var(--color-on-background, #191c21)',
        'text-main': 'var(--color-text-main, #1A1C1E)',
        'surface-container-high': 'var(--color-surface-container-high, #e7e8f0)',
        'on-error': 'var(--color-on-error, #ffffff)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed, #351000)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim, #acc7ff)',
        'surface-container-low': 'var(--color-surface-container-low, #f2f3fc)',
        'surface-container': 'var(--color-surface-container, #ededf6)',
        'primary-container': 'var(--color-primary-container, #0056b3)',
        'surface-container-highest': 'var(--color-surface-container-highest, #e1e2ea)',
        'on-tertiary': 'var(--color-on-tertiary, #ffffff)',
        'outline-variant': 'var(--color-outline-variant, #c2c6d4)',
        'on-primary-container': 'var(--color-on-primary-container, #bbd0ff)',
        'on-surface': 'var(--color-on-surface, #191c21)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant, #7b2f00)',
        background: 'var(--color-background, #f9f9ff)',
        'inverse-primary': 'var(--color-inverse-primary, #acc7ff)',
        tertiary: 'var(--color-tertiary, #722b00)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant, #004491)',
        'on-secondary': 'var(--color-on-secondary, #ffffff)',
        surface: 'var(--color-surface, #f9f9ff)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim, #ffb694)',
        'on-surface-variant': 'var(--color-on-surface-variant, #424752)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant, #00531a)',
        'secondary-container': 'var(--color-secondary-container, #80f98b)',
        'primary-fixed': 'var(--color-primary-fixed, #d7e2ff)',
        'on-error-container': 'var(--color-on-error-container, #93000a)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim, #66df75)',
        'inverse-surface': 'var(--color-inverse-surface, #2e3037)',
        'status-error': 'var(--color-status-error, #DC3545)',
        error: 'var(--color-error, #ba1a1a)',
        secondary: 'var(--color-secondary, #006e25)',
        'surface-variant': 'var(--color-surface-variant, #e1e2ea)',
        'status-warning': 'var(--color-status-warning, #FFC107)',
        'on-secondary-container': 'var(--color-on-secondary-container, #007327)',
        'on-primary-fixed': 'var(--color-on-primary-fixed, #001a40)',
        'on-tertiary-container': 'var(--color-on-tertiary-container, #ffc2a7)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed, #002106)',

        // shadcn-style semantic aliases used by the messaging UI (src/components/blocks).
        // Each one reuses an existing --color-* variable so it stays on the
        // app's own light/dark palette instead of introducing a second one.
        foreground: 'var(--color-text-main, #1A1C1E)',
        card: 'var(--color-surface, #f9f9ff)',
        'card-foreground': 'var(--color-text-main, #1A1C1E)',
        popover: 'var(--color-surface, #f9f9ff)',
        'popover-foreground': 'var(--color-text-main, #1A1C1E)',
        'primary-foreground': 'var(--color-on-primary, #ffffff)',
        'secondary-foreground': 'var(--color-on-secondary, #ffffff)',
        muted: 'var(--color-muted-surface, #f1f5f9)',
        'muted-foreground': 'var(--color-text-secondary, #64748b)',
        accent: 'var(--color-muted-surface, #f1f5f9)',
        'accent-foreground': 'var(--color-text-main, #1A1C1E)',
        destructive: 'var(--color-error, #ba1a1a)',
        'destructive-foreground': 'var(--color-on-error, #ffffff)',
        border: 'var(--color-border, #e2e8f0)',
        input: 'var(--color-border, #e2e8f0)',
        ring: 'var(--color-primary, #003f87)',
        sidebar: 'var(--color-surface, #f9f9ff)',
        'sidebar-foreground': 'var(--color-text-main, #1A1C1E)',
        'sidebar-primary': 'var(--color-primary, #003f87)',
        'sidebar-primary-foreground': 'var(--color-on-primary, #ffffff)',
        'sidebar-accent': 'var(--color-muted-surface, #f1f5f9)',
        'sidebar-accent-foreground': 'var(--color-text-main, #1A1C1E)',
        'sidebar-border': 'var(--color-border, #e2e8f0)',
        'sidebar-ring': 'var(--color-primary, #003f87)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '2rem',
        'stack-lg': '2rem',
        'stack-sm': '0.5rem',
        gutter: '1rem',
        'stack-md': '1rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Poppins', 'sans-serif'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'label-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [forms],
}
