import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'background-alt': 'var(--color-background-alt, #F8F9FA)',
        'tertiary-container': 'var(--color-tertiary-container, #983c00)',
        'surface-tint': 'var(--color-surface-tint, #115cb9)',
        'surface-bright': 'var(--color-surface-bright, #f9f9ff)',
        primary: 'var(--color-primary, #003f87)',
        'error-container': 'var(--color-error-container, #ffdad6)',
        'surface-container-lowest': 'var(--color-surface-container-lowest, #ffffff)',
        'inverse-on-surface': 'var(--color-inverse-on-surface, #f0f0f9)',
        'surface-dim': 'var(--color-surface-dim, #d9d9e2)',
        'secondary-fixed': 'var(--color-secondary-fixed, #83fc8e)',
        'tertiary-fixed': 'var(--color-tertiary-fixed, #ffdbcc)',
        outline: 'var(--color-outline, #727784)',
        'on-primary': 'var(--color-on-primary, #ffffff)',
        'on-background': 'var(--color-on-background, #191c21)',
        'text-main': 'var(--color-text-main, #1A1C1E)',
        'surface-container-high': 'var(--color-surface-container-high, #e7e8f0)',
        'on-error': 'var(--color-on-error, #ffffff)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed, #351000)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim, #acc7ff)',
        'surface-container-low': 'var(--color-surface-container-low, #f2f3fc)',
        'surface-container': 'var(--color-surface-container, #ededf6)',
        'primary-container': 'var(--color-primary-container, #0056b3)',
        'surface-container-highest': 'var(--color-surface-container-highest, #e1e2ea)',
        'on-tertiary': 'var(--color-on-tertiary, #ffffff)',
        'outline-variant': 'var(--color-outline-variant, #c2c6d4)',
        'on-primary-container': 'var(--color-on-primary-container, #bbd0ff)',
        'on-surface': 'var(--color-on-surface, #191c21)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant, #7b2f00)',
        background: 'var(--color-background, #f9f9ff)',
        'inverse-primary': 'var(--color-inverse-primary, #acc7ff)',
        tertiary: 'var(--color-tertiary, #722b00)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant, #004491)',
        'on-secondary': 'var(--color-on-secondary, #ffffff)',
        surface: 'var(--color-surface, #f9f9ff)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim, #ffb694)',
        'on-surface-variant': 'var(--color-on-surface-variant, #424752)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant, #00531a)',
        'secondary-container': 'var(--color-secondary-container, #80f98b)',
        'primary-fixed': 'var(--color-primary-fixed, #d7e2ff)',
        'on-error-container': 'var(--color-on-error-container, #93000a)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim, #66df75)',
        'inverse-surface': 'var(--color-inverse-surface, #2e3037)',
        'status-error': 'var(--color-status-error, #DC3545)',
        error: 'var(--color-error, #ba1a1a)',
        secondary: 'var(--color-secondary, #006e25)',
        'surface-variant': 'var(--color-surface-variant, #e1e2ea)',
        'status-warning': 'var(--color-status-warning, #FFC107)',
        'on-secondary-container': 'var(--color-on-secondary-container, #007327)',
        'on-primary-fixed': 'var(--color-on-primary-fixed, #001a40)',
        'on-tertiary-container': 'var(--color-on-tertiary-container, #ffc2a7)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed, #002106)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '2rem',
        'stack-lg': '2rem',
        'stack-sm': '0.5rem',
        gutter: '1rem',
        'stack-md': '1rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Poppins', 'sans-serif'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'label-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [forms],
}
